# Generated by Django 4.1.3 on 2023-02-26 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='spending_category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='pst.categories'),
        ),
    ]
