# Generated by Django 4.1.3 on 2023-03-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='file',
        ),
    ]
