# Generated by Django 4.1.3 on 2023-03-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RewardPoint',
        ),
    ]
