# Generated by Django 4.1.3 on 2023-03-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='name',
        ),
        migrations.RemoveField(
            model_name='totalbudget',
            name='name',
        ),
    ]
