# Generated by Django 4.1.3 on 2023-03-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_task_points',
            field=models.IntegerField(default=0),
        ),
    ]
