# Generated by Django 4.1.3 on 2023-02-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budget1',
            new_name='Budget',
        ),
    ]
