# Generated by Django 4.1.3 on 2023-03-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='consecutive_login_days',
            field=models.IntegerField(default=1),
        ),
    ]
