# Generated by Django 4.1.3 on 2023-03-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
