# Generated by Django 4.1.6 on 2023-02-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='spendingType',
            field=models.CharField(choices=[('Expenditure', 'Expenditure'), ('Income', 'Income')], default='Expenditure', max_length=30),
        ),
    ]
