# Generated by Django 4.1.3 on 2023-03-15 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0002_remove_user_created_at_remove_user_last_login_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRewardStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(default=False)),
                ('task_points', models.IntegerField(default=0)),
                ('task_type', models.CharField(choices=[('login', 'Login'), ('other', 'Other')], default='login', max_length=10)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pst.day')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pst.dailyrewards')),
            ],
            options={
                'unique_together': {('reward', 'day', 'task_type')},
            },
        ),
        migrations.AddField(
            model_name='dailyrewards',
            name='days',
            field=models.ManyToManyField(through='pst.DailyRewardStatus', to='pst.day'),
        ),
        migrations.AddField(
            model_name='dailyrewards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
