# Generated by Django 4.1.3 on 2023-02-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0002_user_bio_user_birth_date_user_gender_user_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Perfer not to say')], max_length=20),
        ),
    ]
