# Generated by Django 4.1.3 on 2023-03-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0002_user_categories_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories_created',
        ),
    ]
