# Generated by Django 4.1.3 on 2023-03-02 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0002_reward_remove_post_likes_remove_reply_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999' and maximum 15 digits allowed.", regex='^\\d{10,15}$')]),
        ),
    ]
