# Generated by Django 4.1.6 on 2023-02-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0002_alter_spending_spendingtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spending',
            old_name='spendingOwner',
            new_name='spending_owner',
        ),
        migrations.RenameField(
            model_name='spending',
            old_name='spendingType',
            new_name='spending_type',
        ),
    ]
