# Generated by Django 4.1.3 on 2023-02-07 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0003_categories_categories_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='user',
            new_name='owner',
        ),
    ]
