# Generated by Django 4.1.3 on 2023-02-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
