# Generated by Django 4.1.3 on 2023-03-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0003_remove_user_categories_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='default_image',
            field=models.FileField(default='default_reward_image.jpg', upload_to='rewards/'),
        ),
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='rewards/'),
        ),
    ]
