# Generated by Django 4.1.3 on 2023-03-02 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0003_alter_user_address_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999' and maximum 15 digits allowed.", regex='^\\d{10,15}$')]),
        ),
    ]
