# Generated by Django 4.1.6 on 2023-02-01 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0003_rename_spendingowner_spending_spending_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='spending',
            name='descriptions',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
