# Generated by Django 4.1.3 on 2023-03-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0003_alter_post_created_date_alter_reply_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
