# Generated by Django 4.1.3 on 2023-03-17 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0003_dailyrewards_day_dailyrewardstatus_dailyrewards_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('task_points', models.IntegerField(default=0)),
                ('task_type', models.CharField(choices=[('LOGIN', 'Login'), ('POST', 'Post')], default='LOGIN', max_length=10)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pst.day')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pst.dailytask')),
            ],
            options={
                'unique_together': {('task', 'day', 'task_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyrewardstatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyrewardstatus',
            name='day',
        ),
        migrations.RemoveField(
            model_name='dailyrewardstatus',
            name='reward',
        ),
        migrations.DeleteModel(
            name='DailyRewards',
        ),
        migrations.DeleteModel(
            name='DailyRewardStatus',
        ),
        migrations.AddField(
            model_name='dailytask',
            name='days',
            field=models.ManyToManyField(through='pst.DailyTaskStatus', to='pst.day'),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
