# Generated by Django 4.1.3 on 2023-02-07 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0004_rename_user_categories_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='spending_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='pst.categories'),
        ),
    ]
