# Generated by Django 4.1.6 on 2023-02-01 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0004_alter_spending_amount_alter_spending_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='spending',
            name='spending_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pst.categories'),
        ),
    ]
