# Generated by Django 4.1.3 on 2023-03-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0004_reward_default_image_reward_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='default_image',
            field=models.ImageField(default='default_reward_image.jpg', upload_to='rewards/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rewards/'),
        ),
    ]
