# Generated by Django 4.1.3 on 2023-03-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0004_dailytask_dailytaskstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytaskstatus',
            name='completed',
        ),
    ]
