# Generated by Django 4.1.3 on 2023-03-22 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0004_alter_post_created_date_alter_reply_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
