# Generated by Django 4.1.3 on 2023-03-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pst', '0004_rename_user_like_user_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user_liked', 'content_type', 'object_id')},
        ),
    ]
