# Generated by Django 4.1.3 on 2023-02-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0005_spending_spending_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='default_category',
            field=models.BooleanField(default=False, help_text='Designates this category is a default category or notdefault category are not expected to be modified'),
        ),
        migrations.AlterField(
            model_name='spendingfile',
            name='spending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pst.spending'),
        ),
    ]
