# Generated by Django 4.1.3 on 2023-03-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0005_alter_reward_default_image_alter_reward_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='default_image',
            field=models.ImageField(default='3.png', upload_to='user_files/'),
        ),
    ]
