# Generated by Django 4.1.3 on 2023-03-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pst', '0005_remove_reply_likes_alter_like_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_liked',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
