# Generated by Django 4.1.3 on 2023-03-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0007_alter_reward_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='default_image',
            field=models.ImageField(default='rewards/default_reward_image.jpg', upload_to='rewards/'),
        ),
    ]
