# Generated by Django 4.1.3 on 2023-02-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0007_post_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(),
        ),
    ]
