# Generated by Django 4.1.3 on 2023-02-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0008_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
