# Generated by Django 4.1.3 on 2023-03-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0010_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='name',
        ),
    ]
