# Generated by Django 4.1.3 on 2023-03-11 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0011_remove_budget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
