# Generated by Django 4.1.3 on 2023-03-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0012_alter_budget_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='limit',
            field=models.PositiveIntegerField(),
        ),
    ]
