# Generated by Django 4.1.3 on 2023-03-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pst', '0013_alter_budget_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='default_image',
            field=models.FileField(default='rewards/default_reward_image.jpg', upload_to='rewards/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='rewards/'),
        ),
    ]
